### ISSUE TITLE
Separators inside special glob enclosures

### ISSUE THREAD

**Issue by es128** [es128/glob-parent#10]
Originally from https://github.com/es128/path-dirname/issues/1

``` js
> gp('/foo/{,/,bar/baz,qux}/')
'/foo/{,/,bar'
> gp('/foo[a\\\/]/')
'/foo[a\\'
```

is-glob used to return `true` for the presence of `{` or `[`, but it no longer does without the accompanying closing character.

Seems we need to do an extra truncation step over here for any unescaped sets of enclosure characters that might have a path separator inside. Is that only square and curly brackets, or are parentheses an issue as well?

**Comment by jonschlinkert** [comment]
> is-glob used to return true for the presence of { or [, but it no longer does without the accompanying closing character.

This is exactly what I was talking about. We have a double edged sword apparently. Since changes were made to is-glob based on the discussion in [this issue](https://github.com/jonschlinkert/is-glob/issues/4) and specifically based on [this comment](https://github.com/jonschlinkert/is-glob/issues/4#issuecomment-244562745) (which @phated and I both agreed on), glob-parent can't rely on dirname, since dirname will cut the brace in half, and an incomplete brace will now return false from is-glob. 

We have some options:

- re-allow partial sets 
- revert to prior behavior in is-glob
- add an option to is-glob (either "strict" or "loose" or something which would allow partial matches)

I'm in favor of either the first or last option.

**Comment by es128** [comment]
It may not be quite as convenient, but I think is-glob is doing the correct thing now as is, and that we need some code here to accommodate these scenarios.

I have an idea or two about potentially simple solutions that I'll try out.

**Comment by phated** [comment]
Random implementation thoughts:
What if we do the `path-dirname` traversal but concat the parts that are dropped by each pass and run `isGlob` on both the dirname and the concat'ed "basename" until dirname returns false and basename returns true?

**Comment by es128** [comment]
If there are other glob characters on the "basename" side like `/foo/{,/,bar/baz,qux}/*` then that won't work

**Comment by phated** [comment]
@es128 maybe we have to iterate over each segment and track results then return the shortest dirname?

**Comment by es128** [comment]
The idea I'm pursuing currently is regex-based matching and replacing of any unescaped braces or brackets parts of the glob expression. Replace the whole thing with something like `*` prior to getting into the dirname loop.

**Comment by phated** [comment]
@es128 very interesting.  Maybe a separate library called `replace-glob` with signature `replaceGlob(globString, replacerValueOrFunction)`

**Comment by es128** [comment]
@phated Please review #11. I was only targeting braces/brackets expressions which could contain `/` separator characters and therefore cause the problematic split scenario. Afaik extglobs with parentheses cannot.

Doesn't look to me like this operation merits a new lib, but let me know your thoughts on it. I think the kind of thing you're describing would be more sophisticated than this, and I'm not sure what the use case would be. Here I'm taking full advantage of the fact that we will be throwing away all the glob information and therefore don't care what's actually in it.

Much like the first line with appending the `a` this approach may be very dirty or fairly elegant depending on your perspective.
