### ISSUE TITLE
Doesn't return the correct base from non-globby strings

### ISSUE THREAD

**Issue by robwierzbowski** [es128/glob-parent#3]
Given the string `'foo/bar/baz/file.txt'`:

- glob2base returns `'foo/bar/baz'`
- glob-parent returns `'foo/bar/baz/file.txt'`

For complete parity you might want to fix. I want to use glob-parent; not having to add conditionals based on `glob.hasMagic` and `extension !== ''` would make it a more pleasant experience.

**Comment by es128** [comment]
Given the string `'foo/bar/baz'`, glob2base returns `'foo/bar'`, so `extension !== ''` isn't actually going to help you.

Regarding your suggestion, perhaps, but the intention was to strip off glob stuff in order to provide paths that could be used directly in `fs` methods, not to create a version of `path.dirname()` with glob sensitivity. This also wasn't created for the sake of competing with or replacing glob2base, so parity with it hasn't been a goal.

The question I'd like to answer (hopefully in a way that isn't just arbitrary or based upon another lib's choices) is whether it is better or more consistent to ensure the return value is always a parent dir regardless of glob magic.

@jonschlinkert would be interested in your opinion on this

**Comment by robwierzbowski** [comment]
In my project I need some special attention to directory paths; sorry that
part of the example was superfluous. Please disregard.

I've been following the discussions on other repos about replacing
glob2base with glob-parent. If the module is suggested as a replacement
there should be output parity between the two.

If a string of directories returns the equivalent of basename, why wouldn't
a string that ends in a file name? It seems to me that they should both
return the entire string, or both return basename. I could understand use
cases for both, depending on the focus of the module.

Interested in any normalization you decide on.

On Tuesday, September 8, 2015, Elan Shanker <notifications@github.com>
wrote:

> Given the string 'foo/bar/baz', glob2base returns 'foo/bar', so extension
> !== '' isn't actually going to help you.
>
> Regarding your suggestion, perhaps, but the intention was to strip off
> glob stuff in order to provide paths that could be used directly in fs
> methods, not to create a version of path.dirname() with glob sensitivity.
> This also wasn't created for the sake of competing with or replacing
> glob2base, so parity with it hasn't been a goal.
>
> The question I'd like to answer (hopefully in a way that isn't just
> arbitrary or based upon another lib's choices) is whether it is better or
> more consistent to ensure the return value is always a parent dir
> regardless of glob magic.
>
> @jonschlinkert <https://github.com/jonschlinkert> would be interested in
> your opinion on this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/es128/glob-parent/issues/3#issuecomment-138694685>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by jonschlinkert** [comment]
IMHO glob-parent should always return a directory. I think the expectation is that you can take whatever glob-parent returns and use it as a `cwd` for some other method, or prepend it to some other path. If this is indeed the expectation and glob-parent returns a filename in some situations, that should be considered a bug. 

The problem (challenge) is that since node `path` doesn't - and can't - hit the files system to check paths that might not exist yet, we never will have a fool-proof way of knowing if a path is a directory or if the it's supposed to have a basename, etc. For example, given the filepath `foo/bar/baz/`, the node path module will see `baz` as the basename and `foo/bar` as the dirname. regardless of the fact that the path ends in a slash. Same result if we remove the slash.

To come closer to what I think users would expect from glob-parent, perhaps we can do something like this:

```js
module.exports = function globParent(str) {
  if (!isglob(str)) {
    if (str.slice(-1) === '/') {
      return str.slice(0, str.length - 1);
    }
    return path.dirname(str);
  }
  while (isglob(str)) str = path.dirname(str);
  return str;
};
```

this way all of the current assertions will still pass, as well as the following:

```js
it('should return the dirname for a non-glob path', function() {
  assert.equal(gp('path/to/foo.js'), 'path/to');
  assert.equal(gp('path/to/'), 'path/to');
});
```

I think that's a good way to go, the performance hit would be minuscule. 

Is this on the right track?

**Comment by es128** [comment]
I think I'm in agreement here as well that we should do this - always return a parent path of the input. There's no pre-existing expectation about how non-glob paths should be handled, but I think it'll merit a major version bump nonetheless.

Not so sure I like the idea of ascribing significance to the trailing slash though. `path.dirname` doesn't, but glob2base does. So where does that leave us?

As for implementation I was thinking we could still remain just about as simple as before with just

```js
do {str = path.dirname(str)} while (isglob(str));
```

If we want the trailing slash behavior, I'm thinking we don't even need a condition, just start with

```js
// add a character in case of trailing path separator
str += 'a'
```

**Comment by robwierzbowski** [comment]
Adding meaning to the trailing slash seems like an unestablished pattern to me. But I'm only familiar with some of the node ecosystem, so take that with a grain of salt. 

Everything else sounds like a good improvement. :+1:

**Comment by jonschlinkert** [comment]
> Not so sure I like the idea of ascribing significance to the trailing slash though

I was just throwing that out. I can go either way with it. 

fwiw we've been using that convention on other projects like assemble for a while, since it seems like the 100% foolproof to allow the user to say "this is a directory, not a file". otherwise we're just guessing. `path.dirname()` doesn't recognize the slash because regardless of the path, its supposed to return the dirname of that path, which means removing the last segment. 

> If we want the trailing slash behavior, I'm thinking we don't even need a condition, just start with

wouldn't you still need a condition to check for a slash before you add a character? or maybe I misunderstood what you meant. 

my main hesitation about implementing a do-while without any other logic is that we'll end up with:

```js
it('should return the dirname for a non-glob path', function() {
  assert.equal(gp('path/to/foo.js'), 'path/to');
  assert.equal(gp('path/to/'), 'path/to');
  assert.equal(gp('path'), 'path/to'); // is this what a user would expect? `to` is not a glob
}); 
```

**Comment by es128** [comment]
> regardless of the path, its supposed to return the dirname of that path, which means removing the last segment

Perhaps that's what we want here too. idk, I'm having a hard time coming to an objective conclusion one way or the other about it

> wouldn't you still need a condition

Why? It gets discarded either way. The purpose would just be to work around `path.dirname`'s disregard for the trailing slash. So at this point maybe parity with glob2base and the convention you've been following elsewhere is a good enough reason to lean in that direction.

```js
assert.equal(gp('path/to/*.js' + 'a'), 'path/to');
assert.equal(gp('path/to/foo.js' + 'a'), 'path/to');
assert.equal(gp('path/to/' + 'a'), 'path/to');
```

As for the example you added, I think yes, without a trailing slash, we'll always move to a parent dir and it'll be consistent (and consistent with glob2base's behavior). 

```js
assert.equal(gp('path/to'), 'path');
assert.equal(gp('path/to' + 'a'), 'path');
```

**Comment by jonschlinkert** [comment]
> It gets discarded either way.

I see your point, that you were saying `assert.equal(gp('path/to' + 'a')` is okay or desirable. which it might be. I'm not sure either. I'll be working on some permalink stuff for assemble today, it's not the same thing but I remember having to deal with the trailing slash thing the last time I did it. maybe that will spark some memories about pros/cons...
